overrides:
  '@coral-xyz/anchor>toml': '^4.2.0'
  dompurify@<3.4.14: ">=3.4.14"
  js-cookie: 3.0.7
  form-data@<4.0.6: ">=4.0.6"
  postcss@<8.5.18: ">=8.5.18"
  rpc-websockets>ws: ">=8.21.0"

allowBuilds:
  bufferutil: false
  esbuild: true
  utf-8-validate: false
  vue-demi: true
